import type { LifeVitalityTreeMockData } from './lifeVitalityTreeTypes'

export const lifeVitalityTreeMockData: LifeVitalityTreeMockData = {
  title: 'Life Vitality Tree Canvas',
  ownerName: 'Me',
  season: 'mixed',
  headline: '人生生长树 v0.1',
  description: '静态框架阶段：先表达生命力、主线、修复、成果和年轮，不接数据库，不做真实 3D。',
  metrics: [
    { label: '主线筋络', value: '6' },
    { label: '今日叶片', value: '12' },
    { label: '阶段成果', value: '4' },
    { label: '修复事项', value: '3' }
  ],
  nodes: [
    {
      id: 'tree-core',
      title: '整棵人生生长树',
      kind: 'tree',
      status: 'growing',
      path: ['人生生长树'],
      createdAt: '2026-04-27T08:00:00.000Z',
      updatedAt: '2026-04-27T08:00:00.000Z',
      summary: '观察生命力、生长、修复、结果和长期变化的主画布。',
      detail: '这不是任务树、成就树或财富树，而是用于观察一个人的生命结构是否还在持续供给、恢复、连接和创造。',
      nextStep: '继续保持静态框架，下一阶段再讨论类型映射和真实数据接入。',
      x: 50,
      y: 13
    },
    {
      id: 'root-system',
      title: '底层根系',
      kind: 'root',
      status: 'repairing',
      path: ['人生生长树', '树根'],
      createdAt: '2026-04-27T08:10:00.000Z',
      updatedAt: '2026-04-27T08:20:00.000Z',
      summary: '身体、睡眠、财富安全线、关系支持和复盘经验等底层供给。',
      detail: '树根代表外部不容易直接看见、但持续供给人生生长的底层系统，当前不绑定具体数据库字段。',
      nextStep: '后续结合健康、财富、关系和复盘模块确定根系字段。',
      x: 50,
      y: 82
    },
    {
      id: 'soil-review',
      title: '复盘土壤',
      kind: 'soil',
      status: 'stable',
      path: ['人生生长树', '土壤'],
      createdAt: '2026-04-27T08:15:00.000Z',
      updatedAt: '2026-04-27T08:30:00.000Z',
      summary: '失败、落叶和经验沉淀后的养分层。',
      detail: '土壤先作为隐喻保留，用来承接落叶、复盘、旧失败和可转化经验。',
      nextStep: '等待失败复盘和年度复盘结构稳定后再建模。',
      x: 44,
      y: 74
    },
    {
      id: 'trunk-mainline',
      title: '人生主干',
      kind: 'trunk',
      status: 'stable',
      path: ['人生生长树', '树干'],
      createdAt: '2026-04-27T08:20:00.000Z',
      updatedAt: '2026-04-27T08:35:00.000Z',
      summary: '人生主线与营养通道，把底层资源供给枝叶和成果。',
      detail: '树干粗细不直接等于主线数量，而综合表示主线稳定度、长期持续时间和底层供给能力。',
      nextStep: '先用静态筋络表达项目、健康、财富、关系和自我修复等主线。',
      x: 50,
      y: 55
    },
    {
      id: 'vein-project',
      title: '项目筋络',
      kind: 'trunk_vein',
      status: 'growing',
      path: ['人生生长树', '树干', '项目主线'],
      createdAt: '2026-04-27T08:25:00.000Z',
      updatedAt: '2026-04-27T08:40:00.000Z',
      summary: '项目主线正在形成持续供给通道。',
      detail: '筋络用于表达树干内部的不同长期主线，不直接拆成多个主干。',
      nextStep: '后续可映射到 project / node / review 数据，但本轮不接数据库。',
      x: 46,
      y: 48
    },
    {
      id: 'branch-learning',
      title: '学习与能力',
      kind: 'major_branch',
      status: 'growing',
      path: ['人生生长树', '树干', '学习与能力'],
      createdAt: '2026-04-27T08:30:00.000Z',
      updatedAt: '2026-04-27T09:00:00.000Z',
      summary: '主线向外展开为学习、算法、写作和工具能力。',
      detail: '大枝代表主线落地后的模块，可继续分出小枝、叶片、花和果实。',
      nextStep: '用模块视角观察小枝和叶片是否持续更新。',
      x: 35,
      y: 37
    },
    {
      id: 'branch-wealth',
      title: '财富安全线',
      kind: 'major_branch',
      status: 'stable',
      path: ['人生生长树', '树干', '财富安全线'],
      createdAt: '2026-04-27T08:35:00.000Z',
      updatedAt: '2026-04-27T09:05:00.000Z',
      summary: '财富不是主树本体，但会影响根系供给和长期选择。',
      detail: '财富模块未来可作为根系支撑和树干营养压力的输入，但本轮只保留语义边界。',
      nextStep: '保持 Wealth 独立模块，后续再讨论映射关系。',
      x: 67,
      y: 39
    },
    {
      id: 'minor-cpp',
      title: 'C++ 比赛线',
      kind: 'minor_branch',
      status: 'growing',
      path: ['人生生长树', '学习与能力', 'C++ 比赛线'],
      createdAt: '2026-04-27T08:40:00.000Z',
      updatedAt: '2026-04-27T09:10:00.000Z',
      summary: '同一方向在整树视角是小枝，在模块视角可成为局部主干。',
      detail: 'C++ 比赛线可下挂刷题、错题集、比赛复盘和阶段成果。',
      nextStep: '下一阶段可用静态样例表达局部主干。',
      x: 26,
      y: 26
    },
    {
      id: 'leaf-action',
      title: '今日刷题与复盘',
      kind: 'leaf',
      status: 'growing',
      path: ['人生生长树', '学习与能力', 'C++ 比赛线', '今日行动'],
      createdAt: '2026-04-27T09:00:00.000Z',
      updatedAt: '2026-04-27T09:20:00.000Z',
      summary: '叶片代表每日行动、任务和习惯。',
      detail: '叶片用于观察今天是否有行动喂养长期主线，不等同于简单待办清单。',
      nextStep: '后续定义叶片状态细分，当前只保留基础语义。',
      x: 22,
      y: 18
    },
    {
      id: 'flower-prototype',
      title: '阶段原型开花',
      kind: 'flower',
      status: 'growing',
      path: ['人生生长树', '项目主线', 'Life Vitality Tree v0.1'],
      createdAt: '2026-04-27T09:10:00.000Z',
      updatedAt: '2026-04-27T09:25:00.000Z',
      summary: '花代表正在结果前的阶段性小成果。',
      detail: '跑通一次静态 Canvas、类型和 mock 数据，就是 v0.1 的开花状态。',
      nextStep: '完成类型检查和构建后，再进入果实或后续路线判断。',
      x: 77,
      y: 27
    },
    {
      id: 'fruit-workflow',
      title: '可复用工作流',
      kind: 'fruit',
      status: 'harvesting',
      path: ['人生生长树', '项目主线', '工作流果实'],
      createdAt: '2026-04-27T09:20:00.000Z',
      updatedAt: '2026-04-27T09:40:00.000Z',
      summary: '果实代表真正拿到的结果，也可以是可沉淀经验。',
      detail: '一套可复用的双设备协同、文档、验证和 GitHub Sync Gate 可以被视为果实。',
      nextStep: '继续把本轮交付保存到 GitHub 并生成 Mac 接续卡。',
      x: 72,
      y: 18
    },
    {
      id: 'fallen-delay',
      title: '延迟与中断落叶',
      kind: 'fallen_leaf',
      status: 'withered',
      path: ['人生生长树', '时间负债', '落叶'],
      createdAt: '2026-04-27T09:30:00.000Z',
      updatedAt: '2026-04-27T09:45:00.000Z',
      summary: '落叶代表已发生并结束的问题、失败、失控或任务中断。',
      detail: '落叶不做价值审判，后续可以通过复盘进入土壤，转化为根系养分。',
      nextStep: '等时间负债和失败复盘样本稳定后再细化规则。',
      x: 64,
      y: 71
    },
    {
      id: 'ring-2026',
      title: '2026 年轮入口',
      kind: 'annual_ring',
      status: 'stable',
      path: ['人生生长树', '年轮', '2026'],
      createdAt: '2026-04-27T09:40:00.000Z',
      updatedAt: '2026-04-27T09:50:00.000Z',
      summary: '年轮记录年度主线、成果、伤痕和 AI 总结。',
      detail: '年轮是额外衍生视角，不常驻显示在树外部，当前作为入口按钮与静态列表存在。',
      nextStep: '后续等待年度复盘结构稳定后再接真实数据。',
      x: 58,
      y: 52
    }
  ],
  rings: [
    {
      id: 'ring-2024',
      year: 2024,
      title: '主线开始聚合',
      status: 'stable',
      keywords: ['复盘', '基础闭环', '项目意识'],
      summary: '开始把零散行动收束到长期主线中。',
      nextStep: '保留为年轮样例，不做真实年度总结。'
    },
    {
      id: 'ring-2025',
      year: 2025,
      title: '模块分化',
      status: 'growing',
      keywords: ['财富', '时间负债', '双设备协同'],
      summary: '多个模块从主干分化，开始形成大枝。',
      nextStep: '观察主线数量与供给压力之间的关系。'
    },
    {
      id: 'ring-2026',
      year: 2026,
      title: 'Life Vitality Tree 成为主视觉',
      status: 'harvesting',
      keywords: ['人生生长树', '生命力', '年轮'],
      summary: '主视觉从关系图谱转向生命体画布。',
      nextStep: '先完成静态 Canvas，再讨论真实数据映射。'
    }
  ]
}
